import {
  Armchair,
  Baby,
  BedDouble,
  Boxes,
  Building2,
  Calculator,
  Camera,
  Car,
  CircleDot,
  Cog,
  Coffee,
  Croissant,
  DoorOpen,
  Droplets,
  Dumbbell,
  Flower2,
  Footprints,
  Gamepad2,
  Gem,
  Glasses,
  GraduationCap,
  Hammer,
  HardHat,
  Landmark,
  Laptop,
  type LucideIcon,
  Pill,
  Plane,
  Printer,
  Refrigerator,
  Scale,
  Scissors,
  Shirt,
  ShieldCheck,
  ShoppingBasket,
  Smartphone,
  Smile,
  Sparkles,
  Stethoscope,
  Ticket,
  PartyPopper,
  PawPrint,
  Truck,
  Utensils,
  Waves,
  WashingMachine,
  Wrench,
  Zap,
} from "lucide-react";

const ICONS_BY_SLUG: Record<string, LucideIcon> = {
  "kafe-i-restorany": Utensils,
  "kofeyni-i-konditerskie": Coffee,
  pekarni: Croissant,
  "dostavka-edy": Truck,
  "produktovye-magaziny": ShoppingBasket,
  "myasnye-i-rybnye-lavki": Utensils,

  odezhda: Shirt,
  "obuv-biznes": Footprints,
  "tkani-i-atelie": Scissors,
  "yuvelirnye-magaziny": Gem,

  "parikmaherskie-i-barbershopy": Scissors,
  "salony-krasoty-i-spa": Sparkles,
  "nogtevye-studii": Sparkles,
  stomatologii: Smile,
  "medicinskie-kliniki": Stethoscope,
  apteki: Pill,
  optiki: Glasses,

  avtoservisy: Wrench,
  avtomoyki: Droplets,
  shinomontazh: CircleDot,
  avtozapchasti: Cog,
  avtosalony: Car,

  stroymaterialy: HardHat,
  "remont-i-otdelka": Hammer,
  "santehnika-i-elektrika": Zap,
  "okna-i-dveri": DoorOpen,
  "mebel-na-zakaz": Armchair,
  "mebel-i-interer-biznes": Armchair,

  "elektronika-i-telefony": Smartphone,
  "bytovaya-tehnika-biznes": Refrigerator,
  "remont-tehniki": Wrench,
  "kompyutery-i-orgtehnika": Laptop,

  cvety: Flower2,
  "himchistki-i-prachechnye": WashingMachine,
  "veterinarnye-kliniki-i-zoomagaziny": PawPrint,

  "detskie-sady-i-nyani": Baby,
  "kruzhki-i-sekcii-dlya-detey": GraduationCap,
  "kursy-i-repetitory": GraduationCap,
  avtoshkoly: Car,

  "banki-i-mfo": Landmark,
  strahovanie: ShieldCheck,
  "yuridicheskie-uslugi": Scale,
  "buhgalterskie-uslugi": Calculator,
  "gosuslugi-i-mfc": Building2,
  "tipografii-i-pechat": Printer,

  "gostinicy-i-gostevye-doma": BedDouble,
  turagentstva: Plane,

  "razvlekatelnye-centry": Ticket,
  "detskie-razvlecheniya": Gamepad2,
  "sportzaly-i-fitnes": Dumbbell,
  basseyny: Waves,

  "svadebnye-salony": Gem,
  "banketnye-zaly": PartyPopper,
  "foto-i-videosyomka": Camera,
  "organizaciya-prazdnikov": PartyPopper,

  "drugoe-biznes": Boxes,
};

export function BusinessCategoryIcon({ slug, className }: { slug: string; className?: string }) {
  const Icon = ICONS_BY_SLUG[slug] ?? Building2;
  return <Icon className={className} strokeWidth={1.8} />;
}
