import {
  Armchair,
  Baby,
  BedDouble,
  Bike,
  Boxes,
  Brain,
  Building2,
  Calculator,
  Camera,
  Car,
  CircleDot,
  Cog,
  Coffee,
  Croissant,
  DoorOpen,
  Droplets,
  Dumbbell,
  Eye,
  Flame,
  Flower2,
  Footprints,
  Gamepad2,
  Gem,
  Glasses,
  GraduationCap,
  Hammer,
  HandHeart,
  HardHat,
  HeartPulse,
  Home,
  Key,
  Landmark,
  Languages,
  Laptop,
  LayoutGrid,
  type LucideIcon,
  MessageCircle,
  Music,
  Package,
  Paintbrush,
  Palette,
  PenTool,
  Pill,
  Plane,
  Printer,
  Refrigerator,
  Scale,
  Scissors,
  Shirt,
  ShieldCheck,
  ShoppingBasket,
  Smartphone,
  Smile,
  Sparkles,
  Stethoscope,
  Ticket,
  PartyPopper,
  PawPrint,
  Truck,
  Tv,
  Utensils,
  Waves,
  WashingMachine,
  Wind,
  Wrench,
  Zap,
} from "lucide-react";

const ICONS_BY_SLUG: Record<string, LucideIcon> = {
  "kafe-i-restorany": Utensils,
  "kofeyni-i-konditerskie": Coffee,
  pekarni: Croissant,
  "dostavka-edy": Truck,
  "produktovye-magaziny": ShoppingBasket,
  "myasnye-i-rybnye-lavki": Utensils,

  odezhda: Shirt,
  "obuv-biznes": Footprints,
  "tkani-i-atelie": Scissors,
  "yuvelirnye-magaziny": Gem,

  "parikmaherskie-i-barbershopy": Scissors,
  "salony-krasoty-i-spa": Sparkles,
  "nogtevye-studii": Sparkles,
  stomatologii: Smile,
  "medicinskie-kliniki": Stethoscope,
  apteki: Pill,
  optiki: Glasses,

  avtoservisy: Wrench,
  avtomoyki: Droplets,
  shinomontazh: CircleDot,
  avtozapchasti: Cog,
  avtosalony: Car,

  stroymaterialy: HardHat,
  "remont-i-otdelka": Hammer,
  "santehnika-i-elektrika": Zap,
  "okna-i-dveri": DoorOpen,
  "mebel-na-zakaz": Armchair,
  "mebel-i-interer-biznes": Armchair,

  "elektronika-i-telefony": Smartphone,
  "bytovaya-tehnika-biznes": Refrigerator,
  "remont-tehniki": Wrench,
  "kompyutery-i-orgtehnika": Laptop,

  cvety: Flower2,
  "himchistki-i-prachechnye": WashingMachine,
  "veterinarnye-kliniki-i-zoomagaziny": PawPrint,

  "detskie-sady-i-nyani": Baby,
  "kruzhki-i-sekcii-dlya-detey": GraduationCap,
  "kursy-i-repetitory": GraduationCap,
  avtoshkoly: Car,

  "banki-i-mfo": Landmark,
  strahovanie: ShieldCheck,
  "yuridicheskie-uslugi": Scale,
  "buhgalterskie-uslugi": Calculator,
  "gosuslugi-i-mfc": Building2,
  "tipografii-i-pechat": Printer,

  "gostinicy-i-gostevye-doma": BedDouble,
  turagentstva: Plane,

  "razvlekatelnye-centry": Ticket,
  "detskie-razvlecheniya": Gamepad2,
  "sportzaly-i-fitnes": Dumbbell,
  basseyny: Waves,

  "svadebnye-salony": Gem,
  "banketnye-zaly": PartyPopper,
  "foto-i-videosyomka": Camera,
  "organizaciya-prazdnikov": PartyPopper,

  "drugoe-biznes": Boxes,

  "m-santehniki": Droplets,
  "m-elektriki": Zap,
  "m-otdelochniki": Hammer,
  "m-malyary": Paintbrush,
  "m-plitochniki": LayoutGrid,
  "m-svarshiki": Flame,
  "m-krovelshiki": Home,
  "m-mebelshiki": Armchair,
  "m-okna-dveri-kondicionery": Wind,
  "m-raznorabochie": HardHat,

  "m-remont-tehniki": Wrench,
  "m-remont-telefonov": Smartphone,
  "m-kompyuternaya-pomosch": Laptop,
  "m-programmisty": Cog,
  "m-remont-tv-antenn": Tv,

  "m-parikmahery": Scissors,
  "m-manikyur": Sparkles,
  "m-brovi-resnicy": Eye,
  "m-kosmetologi": Smile,
  "m-vizazhisty": Palette,
  "m-massazhisty": HeartPulse,
  "m-tatu": PenTool,

  "m-avtomehaniki": Wrench,
  "m-avtoelektriki": Zap,
  "m-moyka-avto": Droplets,
  "m-shinomontazhniki": CircleDot,
  "m-taksisty": Car,
  "m-evakuatory": Truck,

  "m-repetitory": GraduationCap,
  "m-instruktory-vozhdeniya": Car,
  "m-logopedy": MessageCircle,
  "m-psihologi": Brain,

  "m-foto-video": Camera,
  "m-vedushie": PartyPopper,
  "m-dj-muzykanty": Music,
  "m-povara": Utensils,
  "m-dekor-i-cvety": Flower2,

  "m-nyani": HandHeart,
  "m-kliner": WashingMachine,
  "m-gruzchiki": Package,
  "m-shvei": Scissors,
  "m-rukodelie": Palette,
  "m-zoomaster": PawPrint,
  "m-kurery": Bike,

  "m-yuristy": Scale,
  "m-buhgaltery": Calculator,
  "m-rieltory": Key,
  "m-perevodchiki": Languages,
  "m-trenery": Dumbbell,

  "m-drugoe": Boxes,
};

export function BusinessCategoryIcon({ slug, className }: { slug: string; className?: string }) {
  const Icon = ICONS_BY_SLUG[slug] ?? Building2;
  return <Icon className={className} strokeWidth={1.8} />;
}
